### ISSUE TITLE
Graph - time indicators not aligned with user's time zone (GMT?)

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#158]
1. Browse to http://omnim2m.net using IE 11 and Windows 8.1, login using Patrick's account
2. Select Test Fridge
3. Observe landing page graph

Expected - time markers along x-axis aligned to my time zone

Actual - time markers for the future (which is fine) but are shown having occurred at times that haven't happened here yet. Appears to be GMT.

If it is much work to align graph time by user settings, suggest simply labeling it as GMT (more generally known/understood than Universal Time) and fixing in a later release

![capture - graphtimezone](https://cloud.githubusercontent.com/assets/12534533/8006614/71cfee0c-0b4a-11e5-855e-e4dc3f41558e.PNG)

**Comment by davroth** [comment]
this time w/ highlighting...
![capture - graphtimezone](https://cloud.githubusercontent.com/assets/12534533/8006676/bc4a9644-0b4a-11e5-8e69-f19df738dd7b.PNG)

**Comment by patrickomni** [comment]
Just fiexd this, this morning  I cleared out Cowden which should now show latest.  others will take a few hours.

**Comment by davroth** [comment]
Still seeing data for times that have "not happened yet" in my timezone - Chrome v43, Windows 8.1
![capture - graphtimezone1](https://cloud.githubusercontent.com/assets/12534533/8062942/514491ac-0e87-11e5-97b9-eef8a12e03a6.PNG)

**Comment by patrickomni** [comment]
Chris: in sp_ExecProcessingIncomingData, the date is set based upon the InsertDate, and the GPS coordinate of the Device.  The GPS Coordinate of the device is either delivered by the device, or healed by the sp_ExecProcessingIncomingData using the LastKnownGeoLoc on the DeviceInventory table.   The InsertDate / (MessageDate?) is then updated by the sql function (you'll see the call in sp_ExecProcessIncomingData).

There are a few things that could be going on here.
1) The GPS Coordinate is incorrect in the DeviceInventory
2) The offset (last line in getUTFFromGeo sql function) could be off (note, this offset is there because the SQL is in a different region).
3) We're not presenting or editing the right date, or we're inserting a date from the listener instead of stamping it on the server.  Examine InsertFridgeData stored procedure (or sp_InsertData - ask Frank which one is being called for Fridge).   The server should _own_ insert date, and the device can add message date.  If the messagedate is coming from the device, we shouldn't need to call the offset - I suspect that I'm bluring messagedate (not on all devices, and maybe on none?) and insertdate.

**Comment by christopherdude** [comment]
Guys, I am seeing the Omni Refrigeration / Dan Clem data as the last data point registered at 2:00:31 and it's 2:59 here right now.. This particular one checks in every 2 hours, so I'll see if I have a registered measurement in one hour from now.  If so, this may be fixed.

**Comment by davroth** [comment]
fixed now
