### ISSUE TITLE
Rule UI - log all changes to rules

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#192]
To ensure traceability of who/when rule changes are made, saving a new rule or changing an existing rule will result in a log of the change. The following information will be written in the log:
1.Applicability of the rule (e.g., global account, group, or individual device)
2.Name of account/group/device whose rule is being changed
3.Original rule (if any; this will be blank for the first time a rule is created for an account/group/device
4.New rule - to include thresholds (armed/trigger, temp range, etc), names of users to be notified,, phone numbers
5. Username of person making change 
6. Date/time when change was made (user's timezone)

Please add engineering estimate below and the team will review this in the overall context of V1.1 schedule and features

**Comment by patrickomni** [comment]
I implemented auditing on the rules table but it does not actually answer the overall issue and I hesitate even telling the team it's there.   The reason is that though it logs who changes the rule from within the system, we haven't secured the system so anyone could log in as me and change it or you etc.  Or go through the back end.

Implementing auditing is a great feature;  with the implementation I have in hand, we can at least trace what the data looked like at a point in time, and an educated guess on who changed it, but it really just provides the opportunity for further, incorrect finger pointing.

**Comment by davroth** [comment]
Also need document that describes where to find log, and how to read an entry
