### ISSUE TITLE
Rules UI - when opening any individual device, ensure UI displays the active rule(s)

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#193]
In V1.0 of Omni, the UI presented when an individual device is clicked tells the user there are no rules for the device. This confuses users who are not intimately familiar w/ how Omni Rules work as they may not be aware a global rule exists and applies, so they create a new rule.

If this change request is taken, the UI will not only display any rule active when an individual device is clicked to bring up the Rules UI, it will inform the user where the rule comes from (e.g., Account Global, <Group Name>).

For example if Sempra has a global rule that delivers alerts to George (the checkbox adjacent to George's name is selected) as well as 2 additional phone numbers, then when any user brings up the Rules UI for any individual device (Trap 2-2 for example) or group (Gateway 2 for example), AND there is not an individual rule, then the Rules UI will show George as having been selected as well as the 2 additional phone numbers. 

A message in the Rules UI will inform the user that "Active Rule for this device/group is Account Global Rule. Saving a rule from this window will override the currently Active Rule"

Engineering - please provide rough estimate to implement and test. The team will use that estimate when deciding whether to accept this change request for V1.1

**Comment by patrickomni** [comment]
I implemented the following and am awaiting approval by you (and review by Chris).  I implemented it because it was the easiest way to think it through.   This area is ripe for a different UI as you spec'd but that UI is going to require a lot more work.  As it is, this particular implementation is going to require a lot of testing.

Essentially, if you click on an individual device, or a site, neither of which has a particular rule set to it, but a parent site of that device or site does, the message will now show:

```
                        alertify.alert('The rule for this ' + resultTypeString + ' have been set by a parent site.  If you click the <b>Save rule</b> button, the site level rule will be overridden for this ' + resultTypeString );
```
