### ISSUE TITLE
Data not appearing in graph

### ISSUE THREAD

**Issue by ghost** [patrickomni/omnimobileserver#247]
Description: Data that shows up on a graph covering later dates does not show up on more recent dates (see pictures)
![graph bug 1](https://cloud.githubusercontent.com/assets/13356999/8814139/1c0ab766-2fbe-11e5-89d8-335d5abebbcd.PNG)
![graph bug 2](https://cloud.githubusercontent.com/assets/13356999/8814142/1f08d088-2fbe-11e5-9b1b-b2f2ec55dffe.PNG)

Steps to Reproduce: find a scenario that has data up until recently.  Change graph timeline to at least 30 days ago, if not older.  Then set the graph timeline to less than 30 days ago.

Actual Results:Data that shows up for the most recent three days on these longer graphs does not show up on graphs of the last three days, where the data should be (again, see pictures - easier to see this bug than to read about it).

Expected Results: Data should show up where it exists consistently

**Comment by patrickomni** [comment]
According to the graph, there was no recent data (latest data was 7/15).  Can you clarify if I am missing a point?

**Comment by christopherdengler** [comment]
This item is actually not a bug - it's weird data.  For putting in 3 days on this gives us back ONE point of data --- "([{label:'Demo Unit',data: [[new Date(2015,6, 20, 16, 0, 18), 4]]}])"	-- a SINGLE point.

This single point is just not clearly visible because we chose to remove the dots on the graph, remember?  Therefore, this graph can only do LINES between TWO data points!

**Comment by christopherdengler** [comment]
I'm going to try to adjust it to allow points for when there's only one result.

**Comment by christopherdude** [comment]
This item is actually not a bug - it's weird data. For putting in 3 days on this gives us back ONE point of data --- "([{label:'Demo Unit',data: [[new Date(2015,6, 20, 16, 0, 18), 4]]}])" -- a SINGLE point.

This single point is just not clearly visible because we chose to remove the dots on the graph, remember? Therefore, this graph can only do LINES between TWO (or more) data points!

I have a fix if there's only one item being graphed and there's only one point.  The problem now is, what if there's 2 different graphable items and only one of them has only one point?  I now turn on the points for both lines?  We can't (as far as I know) have one with points and one without, so the points are turned on in rare cases like this.

**Comment by davroth** [comment]
this sounds like #253 which we decided to punt because our customers will rarely (if ever) have a single poknt on the graph

**Comment by davroth** [comment]
pls ignore my comment above - it was intended for a different bug

**Comment by patrickomni** [comment]
This was fixed by adding dots when there is only one point of data.
