### ISSUE TITLE
Deleted alerts table bug

### ISSUE THREAD

**Issue by ghost** [patrickomni/omnimobileserver#252]
Description: If alerts are cleared, then an animated loading symbol will appear over the space where the table used to be and won't go away.  Then, if user tries to open the site/device-level rules interface, then the alerts box will appear over the top of it (see picture).
![deleted alerts bug](https://cloud.githubusercontent.com/assets/13356999/8814850/74bf1cdc-2fc6-11e5-9e6e-7e44992566b2.PNG)

Steps to Reproduce: clear alerts, then open up site/device-level rules

Actual Results: alert box sits over the top of the newly opened dialog box

Expected Results: loading sign should probably go away, and the cleared alerts should not appear over the top of the newly opened dialog box

**Comment by patrickomni** [comment]
Regardless of the spinner, first and foremost, the data is not being cleared.   The log reads:
sp_SetAlertsStatus @ids =

**Comment by christopherdude** [comment]
Ok thx

**Comment by peters95** [comment]
The alerts were not being deleted because the alert ids were not being set after what appeared to be a changed to the JSON returned back. I think it was from using a different JSON lib in the service. Instead of changing the service and introducing additional errors I solved this issue by using javascript regex to extract the correct ID found in the return JSON in a span and then add it back to the old array for the delete to process correctly.

**Comment by patrickomni** [comment]
Ok, this is indeed fixed
