### ISSUE TITLE
Saving user doesn't appear to complete

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#57]
Adding a user does not save the data entered
1. Log on to http://omnistaging.azurewebsites.net as Patrick (IE is browser)
2. Click Edit icon for Reisner, then select Users tab
3. Observe existence of 1 User (the site administrator)
4. Enter data to create a new Account Admin user (data entered was David Rothenberg; dave@omnim2m.com; 14259416927)
5. Click save user button and wait 2+ minutes

Expected - entered data is saved and control returned so that another user can be added in a reasonable amount of time

Actual - control is never returned in a way that allows creation of another user. All 4 buttons in the popup window remain active (cursor changes when hovering). 

when the Cancel button is clicked after waiting 2 minutes, the newly entered data disappears and only 2 buttons remain on the screen. Clicking SAVE at that point returns control to the Add account tab. If I once again select the Users tab, I see the previously entered data. This may be related to Issue 49 (Add user inputs fields are not getting cleared or resets blank.)

![capture - save user](https://cloud.githubusercontent.com/assets/12534533/7737850/6efa7006-ff03-11e4-8d49-8b8fb18f81f9.PNG)

**Comment by CaseyDengler** [comment]
From older post, #49 
Closed older one because this one seemed to have more information, but keeping info in just in case.

Steps to reproduce:
1. Signin without credentials
2. Select any type account to Edit the properties of the account and add new user for the account.
3. Click save user.

Expected : 1)  It should allow user to save new user for the account but here user is not saving when you click on the save user button.

2) If you click cancel button, without saving the user and close the window and  if again you will open edit window for other account and go to user section, here input fields are not getting blank or resets. Previous users input data is remain as it is in the input fields.

![add user](https://cloud.githubusercontent.com/assets/12525836/7727639/b2a318e8-ff27-11e4-9188-85243c77cc78.png)
